prd:
  catalog_name: mlops_prd
  schema_name: giridhar
acc:
  catalog_name: mlops_acc
  schema_name: giridhar
dev:
  catalog_name: mlops_dev
  schema_name: giridhar

id_column:
  - Booking_ID

num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - lead_time
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests
  - arrival_date
  - arrival_year
  - arrival_month

cat_features:
  - type_of_meal_plan
  - required_car_parking_space
  - room_type_reserved
  - market_segment_type


target: booking_status
